[metadata]
page = "N2"
group = "FLOW PATTERN QUICK REFERENCE"
type = "normal"

[[checklists]]
name = "Cockpit safety check"
type = "SF/RD"
diag-pos = [26, 17]
 [[checklists.items]]
left = "CIRCUIT BRK / MDC SW"
right = "CLOSE / OFF 1+2"
 [[checklists.items]]
left = "OVERHEAD SWITCHES"
right = "OFF"
diag-pos = [50, 73]
 [[checklists.items]]
left = "NOSE STEER"
right = "OFF"
diag-pos = [48, 39]
 [[checklists.items]]
left = "LDG GEAR LEVER"
right = "DN"
diag-pos = [51.5, 36]
 [[checklists.items]]
left = "FLT SPOILER LEVER"
right = "RETRACT"
diag-pos = [46, 30]
 [[checklists.items]]
left = "FLAPS LEVER / POSITION"
right = "CHECK / MATCH"
diag-pos = [57.5, 28]
 [[checklists.items]]
left = "LDG GEAR MANUAL RELEASE"
right = "STOW"
diag-pos = [49, 1]
 [[checklists.items]]
left = "ADG MANUAL RELEASE"
right = "STOW"
diag-pos = [52, 1]
 [[checklists.items]]
left = "ADG LAMP TEST"
right = "CHECK"
diag-pos = [54, 2]
 [[checklists.items]]
left = "LOGBOOK / DOCS"
right = "ON BOARD / VERIFIED"
 [[checklists.items]]
left = "SAFETY EQUIPMENT"
right = "CHECK"
 [[checklists.items]]
left = "EXTERNAL CHECK"
right = "COMPLETE"


[[checklists]]
name = "Flight Crew Preflight"
type = "SF/RD"
 [[checklists.items]]
left = "BATTERY MASTER"
right = "ON"
 [[checklists.items]]
left = "BATTERY VOLTS"
right = "MIN 22 VDC"
 [[checklists.items]]
left = ">*< FIREX MONITOR"
right = "TEST"
 [[checklists.items]]
left = ">*< FIRE DETECT WARN & FAIL"
right = "TEST"
 [[checklists.items]]
left = "APU"
right = "START / AVAIL"
 [[checklists.items]]
left = "APU GEN"
right = "ON"
 [[checklists.items]]
left = "AC & DC ELECTRICS"
right = "CHECK"
 [[checklists.items]]
left = "NAV LIGHTS / LOGO LIGHT ON"
right = "ON"
 [[checklists.items]]
left = "COCKPIT LIGHTS"
right = "SET"
 [[checklists.items]]
left = ">*< LAMP TEST"
right = "TEST"
 [[checklists.items]]
left = ">*< DUCT MONITOR"
right = "TEST"
 [[checklists.items]]
left = "FMS DATABASE STATUS"
right = "CYCLE / CHECK"
 [[checklists.items]]
left = "FMS FLIGHT PLAN UPLINK/ATIS "
right = "INITIATE"
 [[checklists.items]]
left = "ANTI-SKID"
right = "ARM / TEST"
 [[checklists.items]]
left = "NOSE DOOR"
right = "CLEAR"
 [[checklists.items]]
left = "HYDRAULIC PUMP 3A"
right = "ON"
 [[checklists.items]]
left = "BRAKE PRESS"
right = "CHECK"
 [[checklists.items]]
left = "PARKING BRAKE"
right = "SET"
 [[checklists.items]]
left = "NOSE DOOR"
right = "CLOSE"
 [[checklists.items]]
left = "HYDRAULIC system"
right = "CHECK/AUTO/3A ON"
 [[checklists.items]]
left = "ELECTRICAL POWER PANEL"
right = "CHECK"
 [[checklists.items]]
left = "AC/DC UTILITY SWITCH"
right = "ON"
 [[checklists.items]]
left = "START / IGN PANEL"
right = "CHECK"
 [[checklists.items]]
left = "FUEL PANEL"
right = "CHECK"
 [[checklists.items]]
left = "APU LCV"
right = "OPEN"
 [[checklists.items]]
left = "10TH STAGE ISOL VALVE"
right = "OPEN"
 [[checklists.items]]
left = "PACKS"
right = "ON"
 [[checklists.items]]
left = "AIR CONDITIONING PANEL"
right = "CHECK"
 [[checklists.items]]
left = "PRESSURIZATION PANEL"
right = "CHECK / SET"
 [[checklists.items]]
left = "BLEED AIR PANEL"
right = "CHECK"
 [[checklists.items]]
left = ">*< SUPP GND WING A/ICE SWITCHES"
right = "OUT"
 [[checklists.items]]
left = ">*< COWL ANTI-ICE SWITCHES"
right = "ON / OFF"
 [[checklists.items]]
left = "ANTI-ICE PANEL"
right = "CHECK / TEST"
[[checklists.items]]
rmk = "Consider testing WSHLD/WIND after TO if OAT is high. See MEL."
 [[checklists.items]]
left = "EMER LIGHTS"
right = "(>*< CHECK) / ARM"
 [[checklists.items]]
left = "PASSENGER SIGNS"
right = "ON / AUTO"
 [[checklists.items]]
left = "ELT"
right = "ARM"
 [[checklists.items]]
left = "GLARESHIELD PANEL"
right = "CHECK"
 [[checklists.items]]
left = "CREW & PAX OXYGEN"
right = "CHECK / ON"
 [[checklists.items]]
left = "DCU WARN PANEL"
right = "CHECK"
 [[checklists.items]]
left = "CVR"
right = "TEST"
 [[checklists.items]]
left = "AUDIO PANELS"
right = "SET"
 [[checklists.items]]
left = ">*< SPS SYSTEM"
right = "CHECK / (ON 1+2)"
 [[checklists.items]]
left = "INTEGRATED STBY INST"
right = "CHECK / SET"
 [[checklists.items]]
left = "CLOCK"
right = "RESET"
 [[checklists.items]]
left = "EFIS & EICAS"
right = "CHECK"
 [[checklists.items]]
left = ">*< MLG BAY OVHT"
right = "CHECK"
 [[checklists.items]]
left = "TAWS WARNING SWITCHES"
right = "OUT / TEST"
 [[checklists.items]]
left = "PITCH & ROLL DISC"
right = "IN / STOW"
 [[checklists.items]]
left = "GND SPOILERS"
right = "AUTO"
 [[checklists.items]]
left = "THRUST REVERSERS"
right = "CHECK / ARM"
 [[checklists.items]]
left = "THRUST LEVERS"
right = "CHECK / SHUTOFF"
 [[checklists.items]]
left = "ENG SPEED SWITCHES"
right = "ON"
 [[checklists.items]]
left = ">*< ENG VIB CHECK"
right = "TEST"
 [[checklists.items]]
left = ">*< AURAL WARN"
right = "CHECK"
 [[checklists.items]]
left = ">*< SMOKE DETECTOR"
right = "TEST"
 [[checklists.items]]
left = "TRIMS (3) MACH TRIM"
right = "(>*< TEST) / SET"
 [[checklists.items]]
left = "YAW DAMPERS"
right = "ENGAGE"
 [[checklists.items]]
left = "REV / INHIBIT SWITCHES"
right = "NORM / OUT"
 [[checklists.items]]
left = "IRS (3)"
right = "ALIGN"
 [[checklists.items]]
left = "CPDLC"
right = "LOGON"
 [[checklists.items]]
left = ">*< TCAS"
right = "TEST"

[[checklists]]
name = "Flight Deck Final Pre-flight"
type = "SF/RD[ALL]"
[[checklists.items]]
left = "ATIS & CLEARANCE"
right = "COPY"
[[checklists.items]]
left = "FMS FLT PLN / WIND / PERF"
right = "PROGRAM"
[[checklists.items]]
left = "TAKEOFF DATA"
right = "SET"
[[checklists.items]]
left = "AVIONICS / CHARTS"
right = "SET"
[[checklists.items]]
left = "FLIGHT INSTRUMENTS"
right = "CHECK / SET"
[[checklists.items]]
rmk = "Perform a logical check of the instruments, navigation source, speeds, flight directors, and thrust ratings. Should be read aloud as an introduction to the departure briefing."
[[checklists.items]]
left = "DEPARTURE BRIEFING"
right = "COMPLETE"
[[checklists.items]]
left = "EMERGENCY PROCEDURES"
right = "REVIEW"
[[checklists.items]]
left = "PINS / COVERS / CHOCKS"
right = "REMOVE"
[[checklists.items]]
left = "CABIN LTS / WATER HTRS / MSTR SEAT"
right = "SET"

[[checklists]]
name = "Engine Start"
type = "SF[F]"
diag-pos = [77, 18]
[[checklists.items]]
left = "Beacon"
right = "On"
diag-pos = [43, 68]
[[checklists.items]]
left = "Fuel Booster Pumps"
right = "On"
diag-pos = [50, 75.5]
[[checklists.items]]
left = "Ignition A/B"
right = "Arm"
diag-pos = [51, 77.5]
[[checklists.items]]
rmk = "A for odd & B for even UTC days of the month"
[[checklists.items]]
left = "Engine 2"
right = " Start"
diag-pos = [49.5, 78.5]
[[checklists.items]]
left = ">*< Fuel Booster Pump"
right = "Test"
#diag-pos = [49, 75.5]
[[checklists.items]]
left = "Engine 1"
right = " Start"
#diag-pos = [48, 78.5]
[[checklists.items]]
rmk = "FO does not need to announce any engine parameters during the start unless they are suspected to exceed the system limit."

[[checklists]]
name = "After Start"
type = "SF[C]"
diag-pos = [26, 15.75]
[[checklists.items]]
rmk = "Captain initiates AFTER START flows by announcing \"Flaps 20, AFTER START\" or \"Hold for Flaps, AFTER START\" for De-Ice."
[[checklists.items]]
left = "Gen 1 & 2"
right = "On"
diag-pos = [44, 76.5]
[[checklists.items]]
left = "Ignition"
right = "Disarm"
diag-pos = [51, 77.5]
[[checklists.items]]
left = "Nose steer"
right = "Arm"
diag-pos = [48, 39]
[[checklists.items]]
left = "GND and FLT Spoilers"
right = "Check/Auto/Stow"
diag-pos = [46, 30]
[[checklists.items]]
left = "APR"
right = "ARM/TEST"
diag-pos = [49, 22]
[[checklists.items]]
left = "ADG UNIT"
right = "TEST"
diag-pos = [54, 2]
[[checklists.items]]
left = "Flight Controls"
right = "Check"
diag-pos = [31.5, 34]

[[checklists]]
name = "After Start"
type = "SF[F]"
diag-pos = [78, 15.75]
[[checklists.items]]
left = "Flaps"
right = "20 (When directed)"
diag-pos = [57.5, 28]
[[checklists.items]]
left = "ATC/TCAS"
right = "TA/RA"
diag-pos = [59, 15]
[[checklists.items]]
left = "Fuel quantity & Balance"
right = "Check"
diag-pos = [40, 47]
[[checklists.items]]
rmk = " Maximum imbalance: 363KG/800LBS in flight, 182KG/400LBS for taxi, takeoff and landing"
[[checklists.items]]
left = "Trims"
right = "3 set for T/O"
diag-pos = [42.5, 50]
[[checklists.items]]
left = "Packs"
right = "ON"
diag-pos = [50, 70.5]
[[checklists.items]]
left = "14TH Stage"
right = "OPEN"
diag-pos = [57.5, 73]
[[checklists.items]]
rmk = "Perform ANTI-ICE SYSTEM TEST if needed."

[[checklists]]
name = ">*< Anti-ice system test"
type = "SF"
diag-pos = [78, 15.75]
[[checklists.items]]
left = "COWL ANTI-ICE"
right = "ON / CHECK 45 SECS"
diag-pos = [57, 69.5]
[[checklists.items]]
left = "COWL ANTI-ICE"
right = "CHECK GREEN ADVISORY"
diag-pos = [45.5, 50]
[[checklists.items]]
left = "SUPP GND WING"
right = "ANTI-ICE TEST ON"
diag-pos = [49, 43]
[[checklists.items]]
left = "SUPP GND WING ANTI-ICE"
right = "TEST OK / OFF"
#diag-pos = [49, 44]
[[checklists.items]]
left = "COWL ANTI-ICE"
right = "OFF"
#diag-pos = [57, 70]
[[checklists.items]]
left = "WING ANTI-ICE"
right = "NORM"
diag-pos = [55, 69.5]
[[checklists.items]]
left = "14TH STAGE ISOL VALVE"
right = "CHECK"
diag-pos = [57.5, 73]
[[checklists.items]]
left = "WING ANTI-ICE"
right = "CHECK / OFF"
#diag-pos = [54, 71]

[[checklists]]
name = "Taxi"
type = "SF[C]"
diag-pos = [27.5, 15.75]
[[checklists.items]]
left = "TAXI lights"
right = "On"
diag-pos = [46, 64]
[[checklists.items]]
left = "Brakes & Steering"
right = "Check"
diag-pos = [12, 37]
[[checklists.items]]
left = "thrust reversers"
right = "check"
diag-pos = [50, 26]
[[checklists.items]]
left = "Wing & Cowl Anti-Ice"
right = "AS RQRD"
diag-pos = [56, 69.5]

[[checklists]]
name = "Before Take-off"
type = "SF[C]"
diag-pos = [27.5, 18]
[[checklists.items]]
left = "continuous ignition"
right = "on"
diag-pos = [52, 78]
[[checklists.items]]
left = "CAS T-O Config OK"
right = "Check"
diag-pos = [45, 50]
[[checklists.items]]
rmk = "Don't forget to release parking brakes."
[[checklists.items]]
left = "EFIS/ATS/EICAS"
right = "Check"
diag-pos = [31, 50]
[[checklists.items]]
raw = """align(center, box(align(left)[Verify the following items:
- Preset HDG
- Speed target (VFTO/AS RQRD)
- FMA active (TO/TO) and armed [LNAV/VNAV]
- Preset ALT
- ATS mode and N1 target, and
- T/O Config OK]))"""
rmk = """Verify the following for the EFIS/ATS/EICAS:
- Preset HDG
- Speed target (VFTO/AS RQRD)
- FMA active (TO/TO) and armed [LNAV/VNAV]
- Preset ALT
- ATS mode and N1 target, and
- T/O Config OK"""
[[checklists.items]]
left = "LDG/Pulse/Recog/ACOLL LTS"
right = "As required"
diag-pos = [43, 64]

[[checklists]]
name = "Before Take-off"
type = "SF[F]"
diag-pos = [78, 15.75]
[[checklists.items]]
rmk = "when cleared to line-up"
[[checklists.items]]
left = "Windshield heat"
right = "LO/HI"
diag-pos = [55, 68]
[[checklists.items]]
left = "Probes"
right = "On"
diag-pos = [58, 68]
[[checklists.items]]
left = "CAS T-O Config OK"
right = "Check"
diag-pos = [45, 48]

[[checklists]]
name = "Descend"
type = "F[ALL]"
diag-pos = [20, 18]
[[checklists.items]]
rmk = "DESCEND flow should be completed by ALL flight crew members before reaching TOD."
[[checklists.items]]
left = "Shoulder Harness"
right = "Secure"
[[checklists.items]]
left = "Passenger Signs"
right = "Auto/On"
diag-pos = [55, 64.5]
[[checklists.items]]
left = "Pressurization"
right = "Set LDG field elev"
diag-pos = [57, 77]
[[checklists.items]]
left = "Fuel Quantity & Balance"
right = "Check"
diag-pos = [39, 47]
[[checklists.items]]
left = "FMS/Landing Data/Charts"
right = "Set/Check"
diag-pos = [44, 37.5]
[[checklists.items]]
left = "Transition Level"
right = "Review/Set"
[[checklists.items]]
left = "Arrival Briefing"
right = "Complete"

[[checklists]]
name = "after landing"
type = "SF[C]"
diag-pos = [27.5, 18]
[[checklists.items]]
rmk = "Captain assumes PF role before 60kt for ground ops after vacating active runway."
[[checklists.items]]
left = "ldg, pulse, Recog lights"
right = "Off"
diag-pos = [43, 64]

[[checklists]]
name = "after landing"
type = "SF[F]"
diag-pos = [78, 20]
[[checklists.items]]
rmk = "First officer does not announce flow pattern items nor the completion of the flow. First officer's primary objective is to assist captain's taxi on the ground."
[[checklists.items]]
left = "Flaps"
right = "retract"
diag-pos = [57.5, 28]
[[checklists.items]]
left = "radar"
right = "stby"
# TODO: add to flow when implemented
diag-pos = [58.5, 20.5]
[[checklists.items]]
left = "ATC/TCAS"
right = "AS RQRD"
diag-pos = [58.5, 15]
[[checklists.items]]
left = "Spoilers"
right = "stowed"
diag-pos = [41.5, 48]
[[checklists.items]]
left = "Anti-collision lights"
right = "off"
diag-pos = [44,67.5]
[[checklists.items]]
left = "Windshield heat"
right = "off"
diag-pos = [55, 68]
[[checklists.items]]
left = "Probes"
right = "off"
diag-pos = [58, 68]
[[checklists.items]]
left = "Cowl anti-ice"
right = "as rqrd"
diag-pos = [57, 70]
[[checklists.items]]
left = "Wing anti-ice"
right = "off"
diag-pos = [54, 70]
[[checklists.items]]
left = "continuous ignition"
right = "off"
diag-pos = [52.5, 78]

[[checklists]]
name = "Go Around"
type = "F[PF]"
[[checklists.items]]
rmk = "Any pilot may initiate the go around flow by announcing \"go around,\" after which PF must execute this flow immediately."
#[[checklists.items]]
#rmk = "CAUTION: If unreliable airspeed is suspected, disregard all reference to TOGA and airspeed. Do not use TOGA switch."
[[checklists.items]]
left = "TOGA switch"
right = "press"
[[checklists.items]]
left = "ATS DISC switch"
right = "press"
[[checklists.items]]
left = "thrust levers"
right = "advance"
#[[checklists.items]]
#rmk = "to the pre-determined go-around N1 setting, while simultaneously pressing the TOGA switch and ATS DISC switch. Consider engaging ATS to trim thrust lever position"
#[[checklists.items]]
#left = "flight spoilers"
#right = "retract"
[[checklists.items]]
left = "pitch attitude"
right = "adjust"
[[checklists.items]]
raw = "align(center)[Do not retract flaps before V#sub[ac] + 10 KIAS.]"
rmk = "Do not retract flaps before Vac + 10 KIAS"
[[checklists.items]]
left = "flight level change"
right = "announce"
[[checklists.items]]
rmk = "Consider to re-engage automation"
[[checklists.items]]
left = "Clean up"
right = "as required"
#[[checklists.items]]
#left = "flaps 20"
#right = "announce"
#[[checklists.items]]
#left = "gear up"
#right = "announce"
#[[checklists.items]]
#left = "flaps up (MIN 400ft AGL)"
#right = "announce"
[[checklists.items]]
rmk = "IMMEDIATE RETURN/AFTER TAKE-OFF NEXT"

[[checklists]]
name = "Discontinued Approach"
type = "F[PF]"
[[checklists.items]]
rmk = "This flow may be applied for cancelling approach above the preselected altitude. The PF initiates this flow by announcing \"cancel approach.\""
[[checklists.items]]
left = "Preselect Altitude"
right = "Set [PM]"
[[checklists.items]]
left = "TOGA Switch"
right = "Press"
[[checklists.items]]
left = "pitch attitude"
right = "adjust"
[[checklists.items]]
rmk = "Consider to use FD Sync"
[[checklists.items]]
left = "autopilot"
right = "engage"
[[checklists.items]]
left = "Guidance Mode"
right = "Set as required"
[[checklists.items]]
left = "Clean up"
right = "as required"
[[checklists.items]]
rmk = "IMMEDIATE RETURN/AFTER TAKE-OFF NEXT"
