[metadata]
# The following colors are used
# Pearl Aqua
color = "#84DCC6"
# # Pale Sky
# color = "#D6EDFF"
# # Icy Blue
# color = "#ACD7EC"
# # Wisteria Blue
# color = "#8B95C9"
# # Jungle Teal
# color = "#478978"
date = "Nov 24 2025"
